/*
This header is auto-generated by gen_input_enum.py script.
Do not edit this file directly.
*/

#pragma once


typedef enum SungMouseBtn {
    SUNG_MOUSE_BTN_LEFT,
    SUNG_MOUSE_BTN_RIGHT,
    SUNG_MOUSE_BTN_MIDDLE,
    SUNG_MOUSE_BTN_EOE,
} SungMouseBtn;

#ifdef __cplusplus
namespace sung {

    enum class MouseBtn {
        left,
        right,
        middle,
        eoe,
    };

}
#endif  // __cplusplus


typedef enum SungMouseAction {
    SUNG_MOUSE_ACTION_MOVE,
    SUNG_MOUSE_ACTION_BTN_UP,
    SUNG_MOUSE_ACTION_BTN_DOWN,
    SUNG_MOUSE_ACTION_MWHEEL_UP,
    SUNG_MOUSE_ACTION_MWHEEL_DOWN,
    SUNG_MOUSE_ACTION_EOE,
} SungMouseAction;

#ifdef __cplusplus
namespace sung {

    enum class MouseAction {
        move,
        btn_up,
        btn_down,
        mwheel_up,
        mwheel_down,
        eoe,
    };

}
#endif  // __cplusplus


typedef enum SungKeyCode {
    SUNG_KEY_CODE_A,
    SUNG_KEY_CODE_B,
    SUNG_KEY_CODE_C,
    SUNG_KEY_CODE_D,
    SUNG_KEY_CODE_E,
    SUNG_KEY_CODE_F,
    SUNG_KEY_CODE_G,
    SUNG_KEY_CODE_H,
    SUNG_KEY_CODE_I,
    SUNG_KEY_CODE_J,
    SUNG_KEY_CODE_K,
    SUNG_KEY_CODE_L,
    SUNG_KEY_CODE_M,
    SUNG_KEY_CODE_N,
    SUNG_KEY_CODE_O,
    SUNG_KEY_CODE_P,
    SUNG_KEY_CODE_Q,
    SUNG_KEY_CODE_R,
    SUNG_KEY_CODE_S,
    SUNG_KEY_CODE_T,
    SUNG_KEY_CODE_U,
    SUNG_KEY_CODE_V,
    SUNG_KEY_CODE_W,
    SUNG_KEY_CODE_X,
    SUNG_KEY_CODE_Y,
    SUNG_KEY_CODE_Z,
    SUNG_KEY_CODE_N0,
    SUNG_KEY_CODE_N1,
    SUNG_KEY_CODE_N2,
    SUNG_KEY_CODE_N3,
    SUNG_KEY_CODE_N4,
    SUNG_KEY_CODE_N5,
    SUNG_KEY_CODE_N6,
    SUNG_KEY_CODE_N7,
    SUNG_KEY_CODE_N8,
    SUNG_KEY_CODE_N9,
    SUNG_KEY_CODE_BACKQUOTE,
    SUNG_KEY_CODE_MINUS,
    SUNG_KEY_CODE_EQUAL,
    SUNG_KEY_CODE_LBRACKET,
    SUNG_KEY_CODE_RBRACKET,
    SUNG_KEY_CODE_BACKSLASH,
    SUNG_KEY_CODE_SEMICOLON,
    SUNG_KEY_CODE_QUOTE,
    SUNG_KEY_CODE_COMMA,
    SUNG_KEY_CODE_PERIOD,
    SUNG_KEY_CODE_SLASH,
    SUNG_KEY_CODE_SPACE,
    SUNG_KEY_CODE_ENTER,
    SUNG_KEY_CODE_BACKSPACE,
    SUNG_KEY_CODE_TAB,
    SUNG_KEY_CODE_ESCAPE,
    SUNG_KEY_CODE_LSHIFT,
    SUNG_KEY_CODE_RSHIFT,
    SUNG_KEY_CODE_LCTRL,
    SUNG_KEY_CODE_RCTRL,
    SUNG_KEY_CODE_LALT,
    SUNG_KEY_CODE_RALT,
    SUNG_KEY_CODE_UP,
    SUNG_KEY_CODE_DOWN,
    SUNG_KEY_CODE_LEFT,
    SUNG_KEY_CODE_RIGHT,
    SUNG_KEY_CODE_EOE,
} SungKeyCode;

#ifdef __cplusplus
namespace sung {

    enum class KeyCode {
        a,
        b,
        c,
        d,
        e,
        f,
        g,
        h,
        i,
        j,
        k,
        l,
        m,
        n,
        o,
        p,
        q,
        r,
        s,
        t,
        u,
        v,
        w,
        x,
        y,
        z,
        n0,
        n1,
        n2,
        n3,
        n4,
        n5,
        n6,
        n7,
        n8,
        n9,
        backquote,
        minus,
        equal,
        lbracket,
        rbracket,
        backslash,
        semicolon,
        quote,
        comma,
        period,
        slash,
        space,
        enter,
        backspace,
        tab,
        escape,
        lshift,
        rshift,
        lctrl,
        rctrl,
        lalt,
        ralt,
        up,
        down,
        left,
        right,
        eoe,
    };

}
#endif  // __cplusplus


typedef enum SungKeyAction {
    SUNG_KEY_ACTION_UP,
    SUNG_KEY_ACTION_DOWN,
    SUNG_KEY_ACTION_EOE,
} SungKeyAction;

#ifdef __cplusplus
namespace sung {

    enum class KeyAction {
        up,
        down,
        eoe,
    };

}
#endif  // __cplusplus
