import os


NAMESPACE = "sung"

DESCRIPTION = """
This header is auto-generated by gen_input_enum.py script.
Do not edit this file directly.
"""

works = dict()

works["mouse btn"] = [
    "left",
    "right",
    "middle",
    "eoe"
]

works["mouse action"] = [
    "move",
    "btn_up",
    "btn_down",
    "mwheel_up",
    "mwheel_down",
    "eoe"
]

works["key code"] = [
    # Alphabets
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
    "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
    # Horizontal numbers
    "n0", "n1", "n2", "n3", "n4", "n5", "n6", "n7", "n8", "n9",
    # Misc in keyboard main area
    "backquote", "minus", "equal", "lbracket", "rbracket", "backslash",
    "semicolon", "quote", "comma", "period", "slash",
    # Special characters
    "space", "enter", "backspace", "tab",
    # No characters
    "escape", "lshift", "rshift", "lctrl", "rctrl", "lalt", "ralt", "up",
    "down", "left", "right",
    # End Of Enum, just for calculating number of elements of Enum class
    "eoe"
]

works["key action"] = [
    "up",
    "down",
    "eoe"
]


class _EnumBuilder:
    def __init__(self, name: str, items: list[str]):
        self.__name_words = name.split()
        self.__items = items

        self.__check_duplicate_items(self.__items)

    def c_enum_name(self) -> str:
        return f"{NAMESPACE.capitalize()}{self.__name_as_pascal_case()}"

    def cpp_enum_name(self) -> str:
        return self.__name_as_pascal_case()

    def gen_c_enum_elements(self):
        c_element_prefix = self.__name_as_constant_case()
        for item in self.__items:
            yield f"{NAMESPACE.upper()}_{c_element_prefix}_{item.upper()}"

    def gen_cpp_enum_elements(self):
        for item in self.__items:
            yield item.lower()

    def __name_as_pascal_case(self) -> str:
        return "".join(x.capitalize() for x in self.__name_words)

    def __name_as_constant_case(self) -> str:
        return "_".join(x.upper() for x in self.__name_words)

    @staticmethod
    def __check_duplicate_items(items: list[str]):
        for i in range(len(items)):
            for j in range(i + 1, len(items)):
                if items[i].lower() == items[j].lower():
                    raise ValueError(f"Duplicate enum item '{items[i]}' vs '{items[j]}'")


def main():
    lines = [
        "/*",
        DESCRIPTION.strip(),
        "*/",
        "",
        "#pragma once",
        "",
    ]

    for name, items in works.items():
        enum_builder = _EnumBuilder(name, items)

        lines.append("")
        lines.append(f"typedef enum {enum_builder.c_enum_name()} {{")
        for item in enum_builder.gen_c_enum_elements():
            lines.append(f"{item},")
        lines.append(f"}} {enum_builder.c_enum_name()};")
        lines.append("")

        # C++

        lines.append("#ifdef __cplusplus")
        lines.append(f"namespace {NAMESPACE} {{")
        lines.append("")

        lines.append(f"enum class {enum_builder.cpp_enum_name()} {{")
        for item in enum_builder.gen_cpp_enum_elements():
            lines.append(f"{item},")
        lines.append("};")
        lines.append("")

        lines.append("}")
        lines.append("#endif  // __cplusplus")
        lines.append("")

    curr_dir = os.path.relpath(os.path.dirname(__file__))
    root_dir = os.path.join(curr_dir, "..")
    include_dir = os.path.join(root_dir, "include", "sung", "basic")
    output_path = os.path.join(include_dir, "input_enum.h")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
